#version 450

struct SplatDepth {
    uint index;
    float z;
};

layout(push_constant) uniform PushConstants {
    mat4 view;
    mat4 proj;
    float near_plane;
};

layout(set = 0, binding = 0) buffer Centroids {
    vec4 centroids[];
};

layout(set = 0, binding = 1) buffer ElementsIn {
    SplatDepth g_elements_in[];
};

layout(set = 0, binding = 2) buffer VisibleCount {
    uint visible_ele_count;
};

layout(set = 0, binding = 3) buffer IndirectDraw {
    uint vertex_count;
    uint instance_count;
    uint first_vertex;
    uint first_instance;
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

shared uint visible_shared;
shared uint group_base_offset;

void main() {
    uint i = gl_GlobalInvocationID.x;
    
    if (gl_LocalInvocationID.x == 0) {
        visible_shared = 0;
    }
    barrier();

    bool is_visible = false;
    float z = 0.0;
    uint local_idx = 0;

    if (i < centroids.length()) {

    mat4 V_P = proj * view; 
    vec4 p_clip = V_P * centroids[i];

    
    if (p_clip.w > 0.0 && p_clip.z >= 0.0 && p_clip.z <= p_clip.w && abs(p_clip.x) <= p_clip.w && abs(p_clip.y) <= p_clip.w) {
        is_visible = true;
        local_idx = atomicAdd(visible_shared, 1);
        
        z = p_clip.w; 
    }
}
    barrier();

  
    if (gl_LocalInvocationID.x == 0 && visible_shared > 0) {
        group_base_offset = atomicAdd(visible_ele_count, visible_shared);
    }
    barrier();

    if (is_visible) {
        uint packed_global_idx = group_base_offset + local_idx;
        
        g_elements_in[packed_global_idx].index = i;
        g_elements_in[packed_global_idx].z = z;
    }

    if (gl_LocalInvocationID == uvec3(0, 0, 0)) {// dont know why it doesnt work with gl_globalinvocationid
        instance_count = visible_ele_count;
    }
}