#version 450

struct SplatDepth {
    uint index;
    float z;
};

layout(push_constant) uniform PushConstants {
    mat4 view;
    mat4 proj;
    float near_plane;
};

layout(set = 0, binding = 0) buffer Centroids {
    vec4 centroids[];
};

layout(set = 0, binding = 1) buffer Scales {
    vec4 scales[];
};

layout(set = 0, binding = 2) buffer ElementsIn {
    SplatDepth g_elements_in[];
};

layout(set = 0, binding = 3) buffer VisibleCount {
    uint visible_ele_count;
};


layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

shared uint visible_shared;
shared uint group_base_offset;

void main() {
    uint i = gl_GlobalInvocationID.x;
    
    if (gl_LocalInvocationID.x == 0) {
        visible_shared = 0;
    }
    barrier();

    bool is_visible = false;
    float z = 0.0;
    uint local_idx = 0;

    if (i < centroids.length()) {

        mat4 V_P = proj * view; 
        vec4 p_clip = V_P * centroids[i];

        float max_scale = max(scales[i].x, max(scales[i].y, scales[i].z));
        float splat_extent = max_scale * 4.5;

        float pad_x = splat_extent * abs(proj[0][0]);
        float pad_y = splat_extent * abs(proj[1][1]);

        if (p_clip.w + splat_extent > near_plane &&
            abs(p_clip.x) <= p_clip.w + pad_x &&
            abs(p_clip.y) <= p_clip.w + pad_y) {
    
            is_visible = true;
            local_idx = atomicAdd(visible_shared, 1);
            z = p_clip.w;
        }

    }
    barrier();

  
    if (gl_LocalInvocationID.x == 0 && visible_shared > 0) {
        group_base_offset = atomicAdd(visible_ele_count, visible_shared);
    }
    barrier();

    if (is_visible) {
        uint packed_global_idx = group_base_offset + local_idx;
        
        g_elements_in[packed_global_idx].index = i;
        g_elements_in[packed_global_idx].z = z;
    }


}